### ISSUE TITLE
Performance benchmark vs other libraries

### ISSUE THREAD

**Issue by sanealytics** [mourner/rbush#99]
This is an awesome library! Beautiful code.

I do have one question though, have you compared it's performance against some other implementations?
E.g. this one -> https://github.com/mrdoob/three.js/blob/master/examples/js/utils/TypedArrayUtils.js#L159

This should be faster on search, but just checking if you've already done something like that.

Thanks

**Comment by mourner** [comment]
There are some performance numbers here: https://github.com/mourner/rbush#performance

Feel free to suggest any libraries to compare to. Three.js one isn't fair to compare to because it's 1) static, 2) points only and 3) 3D. For static use cases, I have a few alternative libraries — https://github.com/mourner/flatbush and https://github.com/mourner/kdbush
